language: r

bioc_required: true
bioc_packages:
  - BiocParallel
r_packages:
  - covr

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: tsPpxEF6menprb4g4Y2ZrtlwhmBNqzjqmELEDDfxD3wwP07jOX2Uj+E9o3N1FqVgFhAiLUWEdr1C1IokBwMqkiNcBGOooT7ZC8VjB5Sp3bywZ68OB3191nmvLSoUrohY3aMug/HFdOwyFUtukrSmZKfp1sh9a96WlEsTRgAGEuU=

env:
  global:
    - _R_CHECK_TIMINGS_="0"
